# 1

In [2]:
import numpy as np


In [5]:
# Generate a 1D numpy array of 10 random integers between 1 and 100
random_integers = np.random.randint(1, 101, size=10)

random_integers

array([72, 82, 39, 82, 24, 14, 16,  6, 72, 64])

In [6]:
# Access and print the first and last element of the array
first_element = random_integers[0]
last_element = random_integers[-1]

first_element, last_element

(72, 64)

In [8]:
# Generate a 2D numpy array of shape (3,3) with random floating-point numbers 
import numpy as np

floating_point = np.random.rand(3, 3)

print(floating_point)


[[0.72254996 0.34131601 0.05046031]
 [0.70737947 0.42408981 0.10363517]
 [0.45162373 0.2517845  0.47356306]]


# 2

In [12]:
# First row
first_row = floating_point [0]
print(first_row)

[0.72254996 0.34131601 0.05046031]


In [13]:
# Last row
Last_row = floating_point [2]
print(Last_row)

[0.45162373 0.2517845  0.47356306]


In [14]:
# First two row and first two coulumns
sub_array = floating_point[:2, :2]
print(sub_array)

[[0.72254996 0.34131601]
 [0.70737947 0.42408981]]


# 3

In [15]:
import numpy as np

# Generate two 1D NumPy arrays of 5 random integers each
array1 = np.random.randint(1, 101, size=5)
array2 = np.random.randint(1, 101, size=5)

# Add the two arrays
result_array = array1 + array2

print("First array:", array1)
print("Second array:", array2)
print("Result of addition:", result_array)



First array: [90 48  8 57  1]
Second array: [ 7 95 87 33 46]
Result of addition: [ 97 143  95  90  47]


In [21]:
# Multiply
print("First array:", array1)
print("Second array:", array2)
print("Result of Multiply:",np.multiply(array1, array2)) 

First array: [90 48  8 57  1]
Second array: [ 7 95 87 33 46]
Result of Multiply: [ 630 4560  696 1881   46]


In [22]:
# Calculate the square of every element in the first array
squared_array1 = np.square(array1)

print("Squared array:", squared_array1)


Squared array: [8100 2304   64 3249    1]


# 4

In [23]:
import numpy as np

# Generate two 2D NumPy arrays
A = np.random.randint(1, 101, size=(2, 3))
B = np.random.randint(1, 101, size=(3, 2))

# Perform matrix multiplication between A and B
result_A,B = A @ B  # Alternatively, np.dot(A, B) can be used

print("Array A:\n", A)
print("Array B:\n", B)
print("Result of matrix multiplication:\n", result_A,B)


Array A:
 [[17 13 49]
 [30 57 20]]
Array B:
 [5601 4194]
Result of matrix multiplication:
 [5880 5502] [5601 4194]


# No, operands could not be broadcast with shapes (2,3)(3,2)